-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHB7ibGzqQEEm2So7
sg0YUy2bMWBndsOsbAyVCG3AVc2gCgYIKoZIzj0DAQehRANCAAQtbZPXFLmJ+Gj0
VgPpCw1pLrUPnXXmLs6q51FDHu4wQBvguP19kalWW0CpsLTfkpFlrqIVjU/DPBhZ
Hnqc8lEl
-----END PRIVATE KEY-----