// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class EuFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkJgU7cjaY9pMihCP7rGLsgKKGaBQLI9c',
    appId: '1:467819533052:web:3734d8510ffe6ec9f23d79',
    messagingSenderId: '467819533052',
    projectId: 'intercom-eu',
    authDomain: 'intercom-eu.firebaseapp.com',
    databaseURL:
        'https://intercom-eu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intercom-eu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzxx5NkuSluJRMyqBftvvYw0lUiORtaA',
    appId: '1:467819533052:android:66206e492eb40258f23d79',
    messagingSenderId: '467819533052',
    projectId: 'intercom-eu',
    databaseURL:
        'https://intercom-eu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intercom-eu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIi23e3_nnFcO-XXvPze1Hq0zcd-_UJs',
    appId: '1:467819533052:ios:4ab85146664f6647f23d79',
    messagingSenderId: '467819533052',
    projectId: 'intercom-eu',
    databaseURL:
        'https://intercom-eu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intercom-eu.appspot.com',
    iosBundleId: 'by.geth.operators',
  );
}
